AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'public/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'

Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: '#80-character-limits'
  Enabled: false

Metrics/MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  StyleGuide: '#short-methods'
  Enabled: false

Metrics/BlockLength:
  Description: 'Avoid long blocks with many lines.'
  Enabled: false

Metrics/AbcSize:
  Enabled: false
